#!/bin/bash
# INSTALL 
# Version: 0.0.5
# Description: INSTALL scripts - Deploy scripts to /opt/davit/bin/
# Load .env variables
set -e
# Source VERSION from .env if it exists
if [ -f .env ]; then
 # shellcheck disable=SC1091
    source .env
fi 

source /opt/davit/bin/davit-logger.sh

# CHECK Dependencies: bash, cp, chmod, rm, echo, source   
# Array of scripts to install
scripts=(
    "gitignore.sh"
)

# if [ "$EUID" -ne 0 ]; then
#   echo "Error: Run as sudo."
#   exit 1
# fi

logger="/opt/davit/bin/davit-logger.sh"
if [ -f "$logger" ]; then
  source "${logger}"
fi

# Get script version
get_script_version(){
  local script="$1"
  local path="$ROOT_DIR/scripts"
  version=$(grep -m1 -E '^# Version:|\\$Id):'  "$script" |\
    grep -m1 -Eo '([0-9]+\.){2}[0-9]+')
 
  echo "$version"
} 


# Function install script
install_script() {
    local script_name=$1
    local path="$ROOT_DIR/scripts"

    local dest_path="${BIN_DIR}"
    extconvention=".sh"
    # validate extension
    if [[ ! "$script_name" != *"$extconvention" ]]; then
        script_ext=""
        else
        script_ext="$extconvention" 
    fi
    # get script version if available
    local script_version
    #echo "LINE 51 (debug): $path/$script_name$script_ext"
    if [ -f "$path/$script_name$script_ext" ]; then
        #script_version=$(grep -oP 'Version: \K[0-9.]+(?=\s*$)' "$path/$script_name$script_ext")
        script_version=$(get_script_version "$path/$script_name$script_ext")
        # echo  "$path/$script_name$script_ext $dest_path"
        cp "$path/$script_name$script_ext" "$dest_path"
        chmod +x "$dest_path/$script_name$script_ext"
        msg=$(printf "Installed %s_v%s%s to %s\n" "$script_name" "${script_version:-"0.0.2"}" "$script_ext" "$BIN_DIR")
        log_info "$msg"
    else
        echo "Error: $src_path does not exist."
        exit 1
    fi
}
# Function to uninstall existing scripts
uninstall_script() {
    local script_name=$1
    local src_path="${BIN_DIR}"

    if [ -f "$src_path/$script_name$script_ext" ]; then
        rm "$src_path/$script_name$script_ext"
        echo "Removed existing $script_name$script_ext from $BIN_DIR"
    fi
}

# Function to install all scripts
install_all_scripts() {
    # Install files in scripts
    for script in "${scripts[@]}"; do
        install_script "$script"
    done     
    log_info "Scripts installed to $BIN_DIR complete. PROJ:${PROJECT_NAME}_v${VERSION:-"0.0.2"}"
       
}
# Function to display help option
help() {
  echo "Script to install or uninstall scripts to /usr/local/bin"
  echo "Usage: $0 [options]"
  echo "Options:"
  echo "  -i        Install scripts"
  echo "  -u        Uninstall existing scripts"
  echo "  -h        Show this help message"
    exit 1
}


#################################################
# Main installation logic
# Check BIN_DIR permissions
if [ ! -d "$BIN_DIR" ] || [ ! -w "$BIN_DIR" ]; then
  echo "Error: $BIN_DIR does not exist or is not writable."
  exit 1
fi

# Parse command line options
while getopts "iuh" opt; do
  case $opt in
    i)
      log_info "Installing scripts..."
      install_all_scripts
      ;;
    u)
      log_info "Uninstalling existing scripts..."
      for script in "${scripts[@]}"; do
          uninstall_script "$script"
      done
      ;;
    h)
      help  
      ;;            
    *)
      help 
      ;;
  esac
done
shift $((OPTIND -1))


# Optionally update stubs in all project roots
#TODO: Fix this: Stubs are not being created correctly


# End of script
